"""Seed the question bank with curated VLSI interview questions.
Run once: python seed_question_bank.py
Re-running is safe — duplicates are skipped by matching question_text.
"""
import database

QUESTIONS = [
    # ═══════════════════════════════════════════════════════════════
    # PHYSICAL DESIGN  (~55 questions)
    # ═══════════════════════════════════════════════════════════════

    # --- Floorplanning ---
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "basic",
     "question_text": "What factors do you consider when choosing the aspect ratio of a chip floorplan?",
     "expected_points": ["IO pad count and placement", "core area vs perimeter tradeoff", "routing channel requirements", "power grid topology", "package constraints"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "basic",
     "question_text": "What is the difference between a hard macro and a soft macro? Give examples of each.",
     "expected_points": ["hard macro has fixed layout (SRAM, IP)", "soft macro is synthesizable RTL", "hard macro placement is manual", "soft macro gets placed by tool", "LEF/DEF representation"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "intermediate",
     "question_text": "You have a design with 20 macros and the utilization target is 70%. Walk me through how you'd decide macro placement order and orientation.",
     "expected_points": ["aspect ratio consideration", "pin proximity", "channel spacing for routing", "power grid alignment", "timing-critical macros near IO"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "intermediate",
     "question_text": "How do you decide the spacing between two macros? What happens if they're too close or too far apart?",
     "expected_points": ["routing channel for signals between them", "power strap continuity", "placement site availability", "halos and keepout margins", "too close causes congestion, too far increases wire delay"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "intermediate",
     "question_text": "You're floorplanning a chip with both analog and digital blocks. What isolation techniques do you use between them?",
     "expected_points": ["guard rings", "separate power domains", "physical separation distance", "substrate isolation", "dedicated IO pads for analog supplies"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "advanced",
     "question_text": "Your floorplan has two large SRAMs that need to talk to each other through combinational logic. One is on the left, one on the right. What timing problems do you expect and how would you fix them without moving the macros?",
     "expected_points": ["long wire delay", "buffer insertion", "repeater strategy", "data path restructuring", "pipeline registers"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "advanced",
     "question_text": "You have a multi-voltage design with three power domains. How does this affect your floorplanning strategy?",
     "expected_points": ["voltage islands with level shifters at boundaries", "isolation cells for power gating", "separate power rings per domain", "always-on regions", "UPF/CPF driven constraints"]},

    # --- Placement ---
    {"domain": "physical_design", "topic": "Placement", "difficulty": "basic",
     "question_text": "After placement you see a congestion hotspot in one corner. What are the first three things you check and what commands would you use in ICC2?",
     "expected_points": ["congestion map analysis", "cell density check", "placement blockage", "keepout regions", "set_congestion_options"]},
    {"domain": "physical_design", "topic": "Placement", "difficulty": "basic",
     "question_text": "What is the difference between coarse placement and legalization? Why is legalization necessary?",
     "expected_points": ["coarse placement optimizes wirelength/timing globally", "legalization snaps cells to rows/sites", "removes overlaps", "respects placement rules", "may slightly degrade QoR"]},
    {"domain": "physical_design", "topic": "Placement", "difficulty": "intermediate",
     "question_text": "What are placement blockages and partial blockages? When would you use each type?",
     "expected_points": ["hard blockage prevents all cell placement", "soft blockage allows buffers only", "partial blockage limits utilization percentage", "use near macros for routing channels", "use for congestion management"]},
    {"domain": "physical_design", "topic": "Placement", "difficulty": "intermediate",
     "question_text": "Your design has a group of cells that form a critical data path. How would you use placement constraints to keep them together without over-constraining the tool?",
     "expected_points": ["create_bounds or group_path", "region constraints vs guide constraints", "bounds too tight hurt congestion", "let tool optimize within bounds", "validate timing improvement"]},
    {"domain": "physical_design", "topic": "Placement", "difficulty": "advanced",
     "question_text": "You have a 500MHz design at 7nm. After placement, WNS is -200ps on 50 paths that all go through the same region. What's your systematic approach?",
     "expected_points": ["path group analysis", "cell density in that region", "placement bounds or guides", "useful skew", "logic restructuring or sizing"]},
    {"domain": "physical_design", "topic": "Placement", "difficulty": "advanced",
     "question_text": "Explain how scan chain reordering during placement affects timing and congestion. What tradeoffs are involved?",
     "expected_points": ["scan reorder reduces scan chain wirelength", "can conflict with functional placement", "shift frequency vs functional frequency", "scan compression considerations", "hold time impact on scan paths"]},

    # --- CTS ---
    {"domain": "physical_design", "topic": "CTS", "difficulty": "basic",
     "question_text": "What is the goal of clock tree synthesis? Why can't you just route the clock like a regular signal?",
     "expected_points": ["minimize skew across all flops", "balanced insertion delay", "regular signal doesn't need balanced arrival", "clock affects all sequential timing", "dedicated buffers/inverters for drive strength"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "basic",
     "question_text": "What is clock skew and how is it different from clock uncertainty? How does each affect timing analysis?",
     "expected_points": ["skew is actual arrival time difference between flops", "uncertainty is margin for jitter and variation", "skew can help or hurt setup/hold", "uncertainty always pessimistic", "tool adds uncertainty as guard band"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "intermediate",
     "question_text": "After CTS, you see 150ps skew on one clock domain but only 20ps on another. Both have similar cell counts. What could cause this difference?",
     "expected_points": ["macro obstruction", "clock tree topology difference", "buffer library selection", "routing congestion", "NDR rules"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "intermediate",
     "question_text": "What are non-default routing rules (NDRs) for clock nets? Why are they used and what's the tradeoff?",
     "expected_points": ["wider width reduces resistance", "double spacing reduces crosstalk", "shielding for noise immunity", "consumes more routing resources", "increases clock net capacitance"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "intermediate",
     "question_text": "You have a design with 5 clock domains. Some share a common source PLL. How do you handle CTS for inter-clock domain paths?",
     "expected_points": ["balance inter-clock skew at shared root", "set_inter_clock_delay_options", "multi-source CTS", "clock domain crossing constraints", "common path pessimism removal"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "advanced",
     "question_text": "You have a generated clock from a divider that feeds 2000 flops. The CTS tool is building a tree from the divider output. What's the risk and how would you handle it?",
     "expected_points": ["source latency variation", "divider output loading", "clock uncertainty budgeting", "set_clock_latency", "generated clock constraints"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "advanced",
     "question_text": "Explain useful skew. How does the CTS tool exploit it, and when can it backfire?",
     "expected_points": ["intentionally skew clock to help setup on critical paths", "borrow time from slack-rich paths", "can create hold violations", "needs careful hold fixing after", "not all tools handle it well across corners"]},

    # --- STA / Timing ---
    {"domain": "physical_design", "topic": "STA", "difficulty": "basic",
     "question_text": "Explain the difference between setup and hold violations. If you fix a setup violation by upsizing a cell, could that create a hold violation somewhere else?",
     "expected_points": ["setup is max delay constraint", "hold is min delay constraint", "upsizing reduces delay", "downstream hold impact", "crosstalk effects"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "basic",
     "question_text": "What are the different timing corners used in STA and why do we need multi-corner analysis?",
     "expected_points": ["SS slow corner for setup", "FF fast corner for hold", "typical for power estimation", "process/voltage/temperature variation", "signoff requires all corners clean"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "intermediate",
     "question_text": "What is on-chip variation (OCV) and how do AOCV and POCV improve on flat OCV derating?",
     "expected_points": ["OCV models process variation within a die", "flat OCV applies uniform derating", "AOCV uses depth/distance based derating", "POCV uses statistical cell-level data", "AOCV/POCV less pessimistic"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "intermediate",
     "question_text": "What is common path pessimism removal (CPPR)? Can you draw a scenario where it matters?",
     "expected_points": ["shared clock path derates cancel out", "launch and capture share buffers before divergence", "without CPPR both get derating creating fake slack", "CPPR removes redundant pessimism on common segment", "significant at high frequency designs"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "intermediate",
     "question_text": "You have a path that crosses from a 500MHz domain to a 250MHz domain. How do you constrain this in SDC and what timing checks apply?",
     "expected_points": ["set_clock_groups or set_false_path if async", "set_multicycle_path if synchronous relationship", "setup check uses most restrictive edge", "hold check on nearest edge", "max_delay/min_delay for async interfaces"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "advanced",
     "question_text": "Your design passes timing at SS/0.72V/125C but fails at FF/0.88V/-40C with hold violations. Why does the fast corner create hold issues?",
     "expected_points": ["fast corner has less delay", "clock and data path imbalance at fast corner", "OCV effects", "AOCV/POCV derating", "temperature inversion below 28nm"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "advanced",
     "question_text": "Explain timing ECO. Your design is post-route with 10 setup violations. Walk me through fixing them without disrupting the rest of the design.",
     "expected_points": ["size up cells on critical path", "insert buffers", "swap to faster Vt cells", "minimize perturbation to placed/routed cells", "incremental route after ECO", "verify no new violations created"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "advanced",
     "question_text": "What is signal integrity impact on timing? How does crosstalk affect setup and hold analysis differently?",
     "expected_points": ["crosstalk can speed up or slow down victim", "same-direction switching helps setup hurts hold", "opposite-direction switching hurts setup helps hold", "SI-aware STA adds delta delay", "glitch analysis separate from delay"]},

    # --- Routing ---
    {"domain": "physical_design", "topic": "Routing", "difficulty": "basic",
     "question_text": "What is the difference between global routing and detail routing? Why is the process split into two stages?",
     "expected_points": ["global routing plans approximate paths through routing tiles", "detail routing assigns exact tracks and vias", "global routing is faster for exploration", "detail routing handles DRC", "congestion estimated in global, resolved in detail"]},
    {"domain": "physical_design", "topic": "Routing", "difficulty": "intermediate",
     "question_text": "After detail routing, you have 200 DRC violations concentrated in one area. What's your debug flow before you start fixing them?",
     "expected_points": ["identify violation types", "check congestion map", "routing layer utilization", "via stacking rules", "NDR or shielding interference"]},
    {"domain": "physical_design", "topic": "Routing", "difficulty": "intermediate",
     "question_text": "What are antenna violations and how do they occur during routing? What are the common fixes?",
     "expected_points": ["charge accumulation during fabrication", "long metal connected to gate during processing", "antenna ratio limit from foundry", "insert antenna diodes", "layer hopping to break antenna", "diode insertion near gate"]},
    {"domain": "physical_design", "topic": "Routing", "difficulty": "advanced",
     "question_text": "You have a signal that needs to be routed 3mm across the chip at 7nm. What signal integrity problems do you expect and how would you handle them?",
     "expected_points": ["resistance and RC delay", "electromigration", "crosstalk from adjacent nets", "shielding or spacing", "repeater insertion", "layer assignment"]},
    {"domain": "physical_design", "topic": "Routing", "difficulty": "advanced",
     "question_text": "At advanced nodes, what are the routing challenges introduced by multi-patterning lithography? How does the router handle them?",
     "expected_points": ["coloring constraints limit track usage", "tip-to-tip and tip-to-side spacing", "cut mask rules", "odd cycle conflicts", "router must be coloring-aware", "increased via resistance with SADP/SAQP"]},

    # --- IR Drop / Power ---
    {"domain": "physical_design", "topic": "IR Drop", "difficulty": "basic",
     "question_text": "What is the difference between static IR drop and dynamic IR drop? Which one is harder to fix and why?",
     "expected_points": ["static is average current DC analysis", "dynamic considers switching activity over time", "dynamic has localized peaks from simultaneous switching", "dynamic harder because it depends on activity patterns", "Ldi/dt effects in dynamic"]},
    {"domain": "physical_design", "topic": "IR Drop", "difficulty": "intermediate",
     "question_text": "Your IR drop analysis shows a 50mV drop at one block corner but only 10mV everywhere else. What physical reasons could cause this localized hot spot?",
     "expected_points": ["insufficient power straps", "missing vias to lower layers", "high switching activity region", "decap cell placement", "power pad location"]},
    {"domain": "physical_design", "topic": "IR Drop", "difficulty": "intermediate",
     "question_text": "What are decoupling capacitors (decaps) and where should you place them? What's the downside of adding too many?",
     "expected_points": ["smooth out voltage fluctuations locally", "place near high-switching regions", "decaps add leakage current", "too many increase standby power", "compete for placement area with logic cells"]},
    {"domain": "physical_design", "topic": "IR Drop", "difficulty": "advanced",
     "question_text": "Your dynamic IR drop simulation shows 100mV transient drop during a burst operation, but the design works in silicon. Why might the simulation be too pessimistic?",
     "expected_points": ["worst-case switching activity assumption", "package model may be overly inductive", "on-die capacitance underestimated", "actual toggle rates lower than VCD", "temperature and process margins stacked"]},

    # --- DRC/LVS ---
    {"domain": "physical_design", "topic": "DRC/LVS", "difficulty": "basic",
     "question_text": "What is the difference between DRC and LVS? Can a design pass DRC but fail LVS?",
     "expected_points": ["DRC checks geometric rules", "LVS checks circuit connectivity matches schematic", "yes, correct geometry but wrong connections passes DRC fails LVS", "open or short nets", "missing devices in layout"]},
    {"domain": "physical_design", "topic": "DRC/LVS", "difficulty": "intermediate",
     "question_text": "LVS is showing a short between VDD and VSS in a region where you didn't make any manual changes. What could cause this and how do you debug it?",
     "expected_points": ["routing overlap on power layers", "via to wrong layer", "standard cell internal short", "antenna diode placement", "layout vs schematic extraction settings"]},
    {"domain": "physical_design", "topic": "DRC/LVS", "difficulty": "advanced",
     "question_text": "After tapeout, the foundry reports a density violation in your metal fill. Your DRC was clean before fill insertion. What went wrong?",
     "expected_points": ["metal fill tool settings don't match foundry rules", "density window size mismatch", "min/max density bounds per layer", "fill near sensitive analog nets", "incremental fill check needed after fill insertion"]},

    # --- Power Planning ---
    {"domain": "physical_design", "topic": "Power Planning", "difficulty": "basic",
     "question_text": "Describe a typical power grid structure from the top metal to the standard cells. What does each layer contribute?",
     "expected_points": ["top metals carry bulk current from pads", "intermediate metals distribute with straps", "lower metals connect to standard cell rails", "via stacks connect layers", "mesh vs stripe topology"]},
    {"domain": "physical_design", "topic": "Power Planning", "difficulty": "intermediate",
     "question_text": "How do you decide the width and pitch of power straps? What happens if they're too narrow or too wide?",
     "expected_points": ["EM current limit determines minimum width", "IR drop target determines pitch", "too narrow causes EM violations", "too wide steals routing resources", "balance with signal routing congestion"]},
    {"domain": "physical_design", "topic": "Power Planning", "difficulty": "advanced",
     "question_text": "You have a power-gated block with header switches. How do you plan the virtual VDD network and what are the key concerns?",
     "expected_points": ["header switch sizing for peak current", "virtual VDD ring and mesh inside gated domain", "rush current during power-on", "isolation cell placement at boundary", "always-on buffer supply routing"]},

    # --- Physical Verification ---
    {"domain": "physical_design", "topic": "Physical Verification", "difficulty": "intermediate",
     "question_text": "What is electromigration (EM) and how do you check for it? What's the typical fix when a wire fails EM?",
     "expected_points": ["metal atoms migrate under current density", "check current density vs foundry limits", "widen the wire", "add parallel paths", "use higher metal layers with thicker metal", "via doubling"]},
    {"domain": "physical_design", "topic": "Physical Verification", "difficulty": "advanced",
     "question_text": "Explain the concept of voltage-aware DRC. Why do advanced nodes need it beyond traditional DRC?",
     "expected_points": ["spacing depends on voltage difference between nets", "high voltage nets need more spacing", "ESD risk at small gaps with high voltage", "foundry provides voltage-dependent rules", "impacts routing near power domains"]},

    # --- ECO ---
    {"domain": "physical_design", "topic": "ECO", "difficulty": "intermediate",
     "question_text": "You need to do a functional ECO to fix a logic bug found after final verification. Walk me through the PnR steps to implement it with minimum disruption.",
     "expected_points": ["get ECO netlist diff", "place new cells near existing logic", "use spare cells or filler replacement", "incremental routing", "re-run timing and DRC on affected region"]},
    {"domain": "physical_design", "topic": "ECO", "difficulty": "advanced",
     "question_text": "Your ECO requires adding 50 new cells but there are no spare cells nearby. The design is at 85% utilization. What are your options?",
     "expected_points": ["resize filler cells to make room", "cell displacement in low-density areas", "use metal-only ECO with programmable logic if available", "negotiate with design team for RTL freeze ECO", "check if logic can be implemented differently with fewer cells"]},

    # ═══════════════════════════════════════════════════════════════
    # ANALOG LAYOUT  (~50 questions)
    # ═══════════════════════════════════════════════════════════════

    # --- Matching ---
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "basic",
     "question_text": "Why is device matching important in analog circuits? Give two examples of circuits where matching is critical.",
     "expected_points": ["mismatch causes offset and gain error", "current mirrors need matching for accurate current copy", "differential pairs need matching for low offset", "affects circuit performance directly", "process variation is the root cause"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "basic",
     "question_text": "What is common centroid layout? Draw a simple example for a 4-transistor arrangement.",
     "expected_points": ["symmetric arrangement around center point", "ABBA or ABAB pattern", "cancels linear gradient effects", "first-order mismatch cancellation", "requires careful routing symmetry"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "intermediate",
     "question_text": "You're laying out a current mirror with 4 transistors that need to match to 0.1%. What techniques do you use and why does each one help?",
     "expected_points": ["common centroid", "interdigitation", "dummy devices", "same orientation", "guard rings", "proximity to avoid gradient effects"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "intermediate",
     "question_text": "What is the Pelgrom model for mismatch? How does it guide your choice of transistor sizing?",
     "expected_points": ["mismatch proportional to 1/sqrt(WL)", "larger devices match better", "Avt and Abeta are process parameters", "threshold voltage mismatch dominates", "diminishing returns at very large sizes"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "advanced",
     "question_text": "Your diff pair is showing 5mV offset after silicon. The layout uses common centroid. What could still cause this mismatch?",
     "expected_points": ["routing asymmetry", "well proximity effect", "STI stress", "metal density asymmetry", "contact resistance variation", "thermal gradient"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "advanced",
     "question_text": "You have a current DAC with 64 unit current sources. How do you arrange them for best matching and what additional layout technique is essential?",
     "expected_points": ["2D common centroid array", "dynamic element matching in circuit", "dummy sources on edges and corners", "symmetric routing tree for bias", "guard rings around entire array", "gradient-canceling arrangement"]},

    # --- Parasitic Effects ---
    {"domain": "analog_layout", "topic": "Parasitic Effects", "difficulty": "basic",
     "question_text": "What are the main parasitic elements in a MOSFET layout and how does each one affect circuit performance?",
     "expected_points": ["gate-drain overlap capacitance (Cgd/Miller)", "source/drain junction capacitance", "interconnect resistance", "well capacitance", "parasitic BJT in CMOS"]},
    {"domain": "analog_layout", "topic": "Parasitic Effects", "difficulty": "intermediate",
     "question_text": "You have a high-speed comparator and the layout engineer routed the input pair with long metal traces. What parasitic effects are you worried about?",
     "expected_points": ["capacitive loading on inputs", "coupling to clock/digital signals", "resistance degrading bandwidth", "substrate coupling", "shielding requirements"]},
    {"domain": "analog_layout", "topic": "Parasitic Effects", "difficulty": "intermediate",
     "question_text": "How does substrate coupling affect sensitive analog circuits? What layout techniques reduce it?",
     "expected_points": ["noise from digital switching couples through substrate", "deep nwell isolation", "guard rings tied to clean supply", "physical distance from digital blocks", "separate substrate taps for analog"]},
    {"domain": "analog_layout", "topic": "Parasitic Effects", "difficulty": "advanced",
     "question_text": "Your PLL VCO is picking up 10MHz spurs that correlate with a nearby switching regulator. The distance is 200um. What layout techniques would you use to isolate it?",
     "expected_points": ["deep nwell isolation", "guard rings", "separate supply domains", "substrate taps", "shielding with ground plane", "physical separation"]},
    {"domain": "analog_layout", "topic": "Parasitic Effects", "difficulty": "advanced",
     "question_text": "Post-layout simulation shows your op-amp unity gain bandwidth dropped from 500MHz to 350MHz. What layout parasitics are most likely responsible?",
     "expected_points": ["parasitic capacitance at high-impedance nodes", "output node loading from routing", "Miller effect amplified by layout Cgd", "interconnect resistance in feedback path", "well junction capacitance"]},

    # --- ESD ---
    {"domain": "analog_layout", "topic": "ESD", "difficulty": "basic",
     "question_text": "What is ESD protection and why is it needed at every IO pad? What are the two main ESD test models?",
     "expected_points": ["electrostatic discharge can destroy gate oxide", "every pad needs discharge path to rails", "HBM (Human Body Model) — 2kV typical", "CDM (Charged Device Model) — faster discharge", "MM (Machine Model) less common now"]},
    {"domain": "analog_layout", "topic": "ESD", "difficulty": "intermediate",
     "question_text": "You need to add ESD protection to a high-speed IO pad running at 5Gbps. What's the tradeoff between protection level and performance?",
     "expected_points": ["ESD diode capacitance vs signal bandwidth", "clamp sizing", "CDM vs HBM requirements", "secondary protection", "placement near pad"]},
    {"domain": "analog_layout", "topic": "ESD", "difficulty": "advanced",
     "question_text": "Your chip is failing CDM testing at 500V on one specific pin. The ESD diodes are correctly sized. What else could be wrong in the layout?",
     "expected_points": ["metal routing resistance to clamp", "insufficient substrate taps near clamp", "local clamp not close enough to pad", "gate oxide exposure from long traces before reaching clamp", "power clamp not firing fast enough"]},

    # --- OTA / Amplifier ---
    {"domain": "analog_layout", "topic": "OTA Design", "difficulty": "basic",
     "question_text": "What are the key layout considerations for a simple five-transistor OTA? Which device pair needs the most attention?",
     "expected_points": ["input diff pair matching is most critical", "active load mirror matching", "symmetric routing", "guard rings for noise isolation", "tail current source placement"]},
    {"domain": "analog_layout", "topic": "OTA Design", "difficulty": "intermediate",
     "question_text": "You're laying out a folded cascode OTA. What's the most critical thing to get right in the layout, and what mistake would kill performance?",
     "expected_points": ["input pair matching", "current mirror matching", "minimize parasitic capacitance at high-impedance nodes", "substrate noise isolation", "symmetric routing"]},
    {"domain": "analog_layout", "topic": "OTA Design", "difficulty": "intermediate",
     "question_text": "How do you handle the compensation capacitor in a two-stage OTA layout? What routing mistakes can degrade phase margin?",
     "expected_points": ["place Cc between first and second stage outputs", "minimize parasitic capacitance at first stage output", "symmetric Cc if differential", "avoid coupling Cc routing to other signals", "nulling resistor placement near Cc"]},
    {"domain": "analog_layout", "topic": "OTA Design", "difficulty": "advanced",
     "question_text": "Your two-stage OTA has 60dB gain on schematic but only 45dB in post-layout. What layout issues could cause this 15dB degradation?",
     "expected_points": ["parasitic capacitance at cascode nodes", "leakage paths", "output impedance reduction from routing", "well proximity effects", "interconnect resistance in signal path"]},

    # --- Bandgap / LDO ---
    {"domain": "analog_layout", "topic": "Bandgap", "difficulty": "basic",
     "question_text": "What is a bandgap reference and why does it need careful layout? What are the two types of components that must match?",
     "expected_points": ["generates temperature-independent voltage ~1.2V", "BJTs must match for delta-VBE", "resistors must match for ratio accuracy", "thermal gradient sensitivity", "common centroid for both"]},
    {"domain": "analog_layout", "topic": "Bandgap", "difficulty": "intermediate",
     "question_text": "How do you lay out the resistors in a bandgap circuit? What type of resistor do you choose and why?",
     "expected_points": ["high-sheet-resistance poly or diffusion resistor", "common centroid for ratio accuracy", "dummy resistors at array edges", "kelvin connections to avoid contact resistance error", "temperature coefficient matching"]},
    {"domain": "analog_layout", "topic": "Bandgap", "difficulty": "advanced",
     "question_text": "Your bandgap reference is showing 5mV variation across process corners in silicon, but simulation showed only 1mV. Where do you look in the layout?",
     "expected_points": ["resistor matching and layout style", "BJT matching", "thermal gradients from nearby power blocks", "routing resistance in reference path", "kelvin connections"]},

    # --- LDO ---
    {"domain": "analog_layout", "topic": "LDO", "difficulty": "intermediate",
     "question_text": "What are the key layout considerations for the pass transistor in an LDO? It's a large PMOS with W=10mm.",
     "expected_points": ["finger width and number of fingers", "uniform current distribution across fingers", "metal width for EM on drain/source", "proximity to output pad", "thermal considerations"]},
    {"domain": "analog_layout", "topic": "LDO", "difficulty": "advanced",
     "question_text": "Your LDO has stability issues that only appear post-layout. Pre-layout simulation is stable. What parasitic elements are you looking for?",
     "expected_points": ["ESR of output cap connection", "parasitic inductance in supply routing", "gate resistance of large pass transistor", "feedback path parasitic capacitance", "bond wire inductance in package model"]},

    # --- ADC / DAC ---
    {"domain": "analog_layout", "topic": "ADC", "difficulty": "basic",
     "question_text": "What makes ADC layout different from general analog layout? What are the key concerns for a 10-bit ADC?",
     "expected_points": ["matching of unit elements to resolution", "noise isolation from digital logic", "clock distribution to samplers", "reference voltage routing", "substrate isolation between analog and digital"]},
    {"domain": "analog_layout", "topic": "ADC", "difficulty": "intermediate",
     "question_text": "You're laying out a flash ADC comparator array. How do you manage the offset across 64 comparators?",
     "expected_points": ["common centroid for each comparator pair", "interleaved arrangement across array", "uniform reference resistor ladder", "balanced clock distribution", "kick-back noise isolation"]},
    {"domain": "analog_layout", "topic": "ADC", "difficulty": "advanced",
     "question_text": "You're laying out a 12-bit SAR ADC capacitor array. How do you ensure the unit capacitor matching is good enough for 12-bit accuracy?",
     "expected_points": ["common centroid arrangement", "dummy capacitors on edges", "uniform metal density", "identical routing to each cap", "symmetry of top and bottom plates"]},
    {"domain": "analog_layout", "topic": "DAC", "difficulty": "intermediate",
     "question_text": "You're laying out a current-steering DAC. How do you route the bias line to 256 unit current sources without creating systematic mismatch?",
     "expected_points": ["symmetric H-tree or binary-weighted routing", "equal impedance to each source", "wide metal for low IR drop", "shielding from digital switching", "avoid voltage gradient across array"]},

    # --- PLL ---
    {"domain": "analog_layout", "topic": "PLL", "difficulty": "basic",
     "question_text": "What are the main blocks in a PLL and which block is the most sensitive to layout?",
     "expected_points": ["PFD, charge pump, loop filter, VCO, divider", "VCO most sensitive to noise", "charge pump matching matters for spurs", "loop filter capacitor matching", "divider is digital and needs isolation"]},
    {"domain": "analog_layout", "topic": "PLL", "difficulty": "intermediate",
     "question_text": "How do you lay out the charge pump in a PLL? What mismatch causes reference spurs?",
     "expected_points": ["up and down current source matching", "common centroid for current mirrors", "switch placement and routing symmetry", "charge sharing from parasitic capacitance", "leakage current mismatch"]},
    {"domain": "analog_layout", "topic": "PLL", "difficulty": "advanced",
     "question_text": "Your PLL jitter is 3x worse in silicon compared to simulation. The VCO frequency is correct. Where do you look?",
     "expected_points": ["supply noise coupling to VCO", "substrate noise injection", "charge pump mismatch causing spurs", "loop filter parasitic resistance", "reference clock quality degradation"]},

    # --- Power / Layout Techniques ---
    {"domain": "analog_layout", "topic": "Power Layout", "difficulty": "intermediate",
     "question_text": "How do you handle power routing for a mixed-signal chip? What are star and mesh topologies?",
     "expected_points": ["separate analog and digital supplies", "star topology for sensitive blocks avoids shared impedance", "mesh gives lower overall resistance", "star prevents noise coupling between blocks", "decoupling at each block"]},
    {"domain": "analog_layout", "topic": "Guard Rings", "difficulty": "basic",
     "question_text": "What is a guard ring and why is it used in analog layout? What types exist?",
     "expected_points": ["ring of substrate/well contacts around device", "collects minority carriers", "reduces latchup risk", "N-well guard ring for PMOS", "P-sub guard ring for NMOS", "reduces substrate noise coupling"]},
    {"domain": "analog_layout", "topic": "Guard Rings", "difficulty": "intermediate",
     "question_text": "You have a sensitive analog circuit with both PMOS and NMOS devices. How do you structure the guard rings and well taps?",
     "expected_points": ["inner P+ guard ring for NMOS in p-substrate", "inner N+ guard ring for PMOS in n-well", "outer P+ ring connecting to ground", "well tap frequency for latchup prevention", "deep nwell for additional isolation"]},

    # --- Latchup ---
    {"domain": "analog_layout", "topic": "Latchup", "difficulty": "basic",
     "question_text": "What is latchup in CMOS circuits? What causes it and how does the layout prevent it?",
     "expected_points": ["parasitic PNPN thyristor structure", "triggered by current injection exceeding holding current", "substrate/well taps every N microns", "guard rings break the feedback loop", "ESD events can trigger it"]},
    {"domain": "analog_layout", "topic": "Latchup", "difficulty": "intermediate",
     "question_text": "The foundry rule says substrate taps every 15um. Your design has analog blocks with sensitive transistors. Do you just follow the rule, or do something more?",
     "expected_points": ["15um is minimum — go denser near sensitive circuits", "continuous guard rings for critical blocks", "butting contacts for compact tapping", "more taps near IO where injection risk is higher", "deep nwell for additional isolation"]},

    # --- Process ---
    {"domain": "analog_layout", "topic": "Process Effects", "difficulty": "intermediate",
     "question_text": "What is the well proximity effect (WPE) and how does it affect analog layout?",
     "expected_points": ["threshold voltage shifts near well edges", "caused by ion implant scattering", "transistors at different distances from well edge have different Vt", "affects matching", "keep matched devices same distance from well edge"]},
    {"domain": "analog_layout", "topic": "Process Effects", "difficulty": "advanced",
     "question_text": "At 28nm and below, what is STI stress and how does it affect your transistor layout for matched devices?",
     "expected_points": ["shallow trench isolation causes mechanical stress", "stress varies with distance from STI edge", "affects carrier mobility and Vt", "dummy poly/fingers at edges equalize stress", "LOD (Length of OD) effect on matched pairs"]},

    # ═══════════════════════════════════════════════════════════════
    # DESIGN VERIFICATION  (~50 questions)
    # ═══════════════════════════════════════════════════════════════

    # --- UVM ---
    {"domain": "design_verification", "topic": "UVM", "difficulty": "basic",
     "question_text": "Walk me through a UVM testbench architecture for an AXI slave. What components do you need and how do they connect?",
     "expected_points": ["agent with driver/monitor/sequencer", "scoreboard", "reference model", "coverage collector", "virtual interface"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "basic",
     "question_text": "What is the difference between a UVM driver and a UVM monitor? Can a monitor be active?",
     "expected_points": ["driver sends stimulus to DUT via interface", "monitor observes signals passively", "monitor should never drive signals", "monitor sends transactions via analysis port", "active/passive agent concept"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "basic",
     "question_text": "What are UVM phases? Why does UVM use a phased approach instead of just running everything in an initial block?",
     "expected_points": ["build, connect, run phases", "build phase creates components bottom-up", "connect phase links TLM ports", "run phase executes test", "phasing ensures all components exist before connecting"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "intermediate",
     "question_text": "Your UVM scoreboard is showing false mismatches on back-to-back AXI write transactions. What could cause this?",
     "expected_points": ["ordering issue in scoreboard", "write response vs data arrival race", "TLM FIFO ordering", "missing handshake tracking", "out-of-order completion support"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "intermediate",
     "question_text": "How do you use UVM sequences and virtual sequences? When would you need a virtual sequence?",
     "expected_points": ["sequence generates transaction stream for one interface", "virtual sequence coordinates multiple sequencers", "cross-interface scenarios need virtual sequences", "virtual sequencer holds handles to real sequencers", "layered sequences for protocol complexity"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "intermediate",
     "question_text": "What is the UVM register abstraction layer (RAL)? How does it help in verifying registers?",
     "expected_points": ["mirrors hardware register map in software", "provides read/write/mirror/predict methods", "auto-generates from IP-XACT or RALF", "front-door via bus agent, back-door via HDL path", "built-in coverage for register access patterns"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "advanced",
     "question_text": "You need to verify a DMA engine that can do 8 simultaneous transfers across 4 AXI masters. How do you structure the scoreboard to avoid false passes?",
     "expected_points": ["per-channel tracking", "address range mapping", "out-of-order completion handling", "end-to-end data integrity check", "transfer boundary tracking"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "advanced",
     "question_text": "Your testbench has a memory leak — simulation slows down over time. What UVM coding patterns could cause this and how do you fix it?",
     "expected_points": ["transaction objects not being freed", "analysis FIFOs growing unbounded", "sequence items stored in queues without cleanup", "factory overrides creating extra objects", "use objection drain time to clean up"]},

    # --- Coverage ---
    {"domain": "design_verification", "topic": "Coverage", "difficulty": "basic",
     "question_text": "What is the difference between code coverage and functional coverage? Can you have 100% code coverage and still miss bugs?",
     "expected_points": ["code coverage measures executed lines/branches/conditions", "functional coverage measures specification coverage", "100% code coverage doesn't mean all scenarios tested", "missing spec-level scenarios is the gap", "both needed for sign-off"]},
    {"domain": "design_verification", "topic": "Coverage", "difficulty": "intermediate",
     "question_text": "Your functional coverage is stuck at 85% after 10,000 tests. What's your systematic approach to close the remaining 15%?",
     "expected_points": ["analyze uncovered bins", "check if bins are unreachable", "constrained random refinement", "directed tests for corner cases", "cross coverage analysis"]},
    {"domain": "design_verification", "topic": "Coverage", "difficulty": "intermediate",
     "question_text": "How do you write effective cross coverage without creating an explosion of bins? Give an example.",
     "expected_points": ["select only meaningful signal combinations", "use ignore_bins to exclude illegal states", "binsof to select specific cross points", "keep signal widths manageable", "merge bins where fine granularity not needed"]},
    {"domain": "design_verification", "topic": "Coverage", "difficulty": "advanced",
     "question_text": "You have cross coverage between 3 signals, each with 8 values. That's 512 bins but only 50 are legal. How do you handle this in your covergroup?",
     "expected_points": ["ignore_bins for illegal combinations", "bins based on legal spec", "wildcard bins", "cross with binsof", "avoid covergroup explosion"]},
    {"domain": "design_verification", "topic": "Coverage", "difficulty": "advanced",
     "question_text": "How do you use coverage-driven verification to guide constrained random tests? What's the feedback loop?",
     "expected_points": ["analyze coverage holes after regression", "adjust constraints to target uncovered scenarios", "weighted distribution towards uncovered bins", "directed sequences for hard-to-hit corners", "iterate until coverage closure"]},

    # --- Assertions ---
    {"domain": "design_verification", "topic": "Assertions", "difficulty": "basic",
     "question_text": "What is the difference between immediate and concurrent assertions in SystemVerilog? When do you use each?",
     "expected_points": ["immediate assertions check at current simulation time", "concurrent assertions span multiple clock cycles", "immediate used in procedural blocks", "concurrent used for protocol checking over time", "concurrent use sequences and properties"]},
    {"domain": "design_verification", "topic": "Assertions", "difficulty": "intermediate",
     "question_text": "Write an SVA assertion that checks: after a request is asserted, grant must come within 1-10 cycles, and data must be valid on the same cycle as grant.",
     "expected_points": ["sequence with ##[1:10]", "consequent checking data validity", "property with disable iff reset", "concurrent vs immediate", "proper clock specification"]},
    {"domain": "design_verification", "topic": "Assertions", "difficulty": "intermediate",
     "question_text": "What are cover properties and cover sequences? How do they differ from assert properties?",
     "expected_points": ["cover checks if a scenario occurs at least once", "assert checks that a property always holds", "cover for functional coverage via SVA", "cover doesn't fail the test, just reports hits", "useful for checking reachability"]},
    {"domain": "design_verification", "topic": "Assertions", "difficulty": "advanced",
     "question_text": "Your assertion for AXI WLAST is passing but real silicon has a bug where WLAST comes one beat early. Why didn't your assertion catch it?",
     "expected_points": ["assertion may not check burst length correlation", "WLAST timing vs WVALID", "counter-based checking needed", "assertion completeness gap", "need to cross-check with AWLEN"]},
    {"domain": "design_verification", "topic": "Assertions", "difficulty": "advanced",
     "question_text": "How do you write liveness assertions? Give an example of a liveness check for a FIFO that should never stay full for more than 100 cycles.",
     "expected_points": ["liveness means something eventually happens", "use strong operator ##[0:100]", "or use |-> ##[1:$] eventually", "full signal should deassert within bound", "unbounded liveness can cause simulation issues"]},

    # --- Formal Verification ---
    {"domain": "design_verification", "topic": "Formal Verification", "difficulty": "basic",
     "question_text": "What is formal verification and how is it different from simulation-based verification? When would you use it?",
     "expected_points": ["exhaustive proof of properties without test vectors", "mathematically proves or disproves assertions", "finds corner cases simulation misses", "limited by state space complexity", "best for control logic, arbiters, protocols"]},
    {"domain": "design_verification", "topic": "Formal Verification", "difficulty": "intermediate",
     "question_text": "You're using formal to verify an arbiter. After 2 hours it says 'bounded proof to depth 50'. Is your design verified? What does this mean?",
     "expected_points": ["bounded proof is not full proof", "state space not exhausted", "need unbounded proof or sufficient depth justification", "complexity may need abstractions", "counterexample interpretation"]},
    {"domain": "design_verification", "topic": "Formal Verification", "difficulty": "intermediate",
     "question_text": "What are assumptions in formal verification? What happens if you over-constrain or under-constrain them?",
     "expected_points": ["assumptions restrict input space to legal scenarios", "over-constrain misses valid bugs (false passes)", "under-constrain causes false failures", "assumptions must match spec precisely", "use cover to check assumptions aren't vacuous"]},
    {"domain": "design_verification", "topic": "Formal Verification", "difficulty": "advanced",
     "question_text": "You need to formally verify a 64KB cache controller. Formal can't handle the full design. What abstraction techniques do you use?",
     "expected_points": ["reduce memory depth symbolically", "abstract data path, focus on control", "cut environment with assumptions", "use helper logic for invariants", "compositional verification of sub-blocks"]},

    # --- Debug ---
    {"domain": "design_verification", "topic": "Debug", "difficulty": "basic",
     "question_text": "Your simulation is failing at time 0 before any stimulus is applied. What are the common causes?",
     "expected_points": ["reset not asserted at start", "uninitialized signals causing X propagation", "missing clock generation", "interface not connected", "initial block timing issue"]},
    {"domain": "design_verification", "topic": "Debug", "difficulty": "intermediate",
     "question_text": "Your simulation passes for 1000 seeds but fails on seed 1001 at cycle 500,000. How do you debug this efficiently?",
     "expected_points": ["reproduce with same seed", "add targeted logging around failure cycle", "binary search on cycle count", "check UVM message severity", "waveform dump window around failure"]},
    {"domain": "design_verification", "topic": "Debug", "difficulty": "intermediate",
     "question_text": "You have an intermittent test failure that occurs in about 1 in 50 runs. How do you approach debugging a non-deterministic failure?",
     "expected_points": ["collect seeds from all failing runs", "look for common patterns in failure signature", "check for race conditions in testbench", "add protocol checkers and assertions", "try running with different simulator optimizations off"]},
    {"domain": "design_verification", "topic": "Debug", "difficulty": "advanced",
     "question_text": "A gate-level simulation fails but RTL passes with the same test. What categories of bugs cause this and how do you narrow it down?",
     "expected_points": ["timing-related issues", "uninitialized X propagation", "SDF annotation errors", "library cell behavior differences", "reset sequence differences", "race conditions in gates"]},

    # --- SystemVerilog ---
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "basic",
     "question_text": "What's the difference between a mailbox and a queue in SystemVerilog? When would you use each in a UVM testbench?",
     "expected_points": ["mailbox is thread-safe FIFO", "queue is not blocking", "mailbox for inter-thread communication", "queue for data storage", "mailbox has put/get blocking semantics"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "basic",
     "question_text": "What is the difference between logic and reg in SystemVerilog? Can you use logic everywhere?",
     "expected_points": ["logic is 4-state, replaces both wire and reg", "logic can be driven by continuous or procedural", "logic cannot have multiple drivers", "wire still needed for multi-driver nets", "reg is Verilog legacy term"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "intermediate",
     "question_text": "Explain the difference between blocking and non-blocking assignments. What happens if you use blocking assignments in an always_ff block?",
     "expected_points": ["blocking executes sequentially", "non-blocking schedules update at end of time step", "blocking in always_ff can cause race conditions", "simulation may not match synthesis behavior", "non-blocking required for sequential logic modeling"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "intermediate",
     "question_text": "What are parameterized classes in SystemVerilog? How would you use them in a UVM testbench?",
     "expected_points": ["generic class with type or value parameters", "reusable across different data types", "UVM transaction classes often parameterized", "type parameters for interface-agnostic components", "factory registration with parameterized classes"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "advanced",
     "question_text": "What are the different types of constraints in SystemVerilog? How do solve...before, dist, and inside interact with the constraint solver?",
     "expected_points": ["solve before controls solving order", "dist assigns probability weights", "inside constrains to a set of values", "constraints are solved simultaneously by default", "solve before can affect distribution of dependent variables"]},

    # --- Constrained Random ---
    {"domain": "design_verification", "topic": "Constrained Random", "difficulty": "basic",
     "question_text": "What is constrained random verification? Why is it preferred over directed testing for complex designs?",
     "expected_points": ["random stimulus within legal bounds", "finds corner cases humans don't think of", "covers more state space faster", "constraints keep tests legal", "directed tests still needed for specific scenarios"]},
    {"domain": "design_verification", "topic": "Constrained Random", "difficulty": "intermediate",
     "question_text": "Your constrained random test keeps generating the same transaction patterns. What could be wrong with your constraints?",
     "expected_points": ["over-constrained — too few valid solutions", "solver bias toward certain values", "missing dist constraints for uniformity", "contradicting constraints reduce solution space", "check with solve_failed callback"]},
    {"domain": "design_verification", "topic": "Constrained Random", "difficulty": "advanced",
     "question_text": "You need to generate random AXI burst transactions that are always aligned and don't cross 4KB boundaries. Write the constraint and explain why 4KB matters.",
     "expected_points": ["4KB boundary is AXI spec requirement", "address + length must not cross boundary", "constraint on address alignment to burst size", "modular arithmetic in constraint", "wrap burst type has additional rules"]},

    # --- Protocol Verification ---
    {"domain": "design_verification", "topic": "Protocol Verification", "difficulty": "basic",
     "question_text": "What are the key signals in an AXI handshake? What rule must never be violated?",
     "expected_points": ["VALID and READY handshake", "VALID must not depend on READY", "READY can depend on VALID", "transfer occurs when both asserted", "deadlock if VALID waits for READY"]},
    {"domain": "design_verification", "topic": "Protocol Verification", "difficulty": "intermediate",
     "question_text": "How would you verify that an AXI slave correctly handles out-of-order read responses? What checks are needed?",
     "expected_points": ["track outstanding read requests by ID", "responses must match request address/size", "RLAST must come on final beat", "ID ordering within same ID must be maintained", "scoreboard indexed by transaction ID"]},
    {"domain": "design_verification", "topic": "Protocol Verification", "difficulty": "advanced",
     "question_text": "You're verifying a cache coherence protocol (MOESI). What are the most critical scenarios to test and what verification methodology would you use?",
     "expected_points": ["all state transitions M→O→E→S→I", "write-back and invalidation races", "snoop request concurrent with local access", "multi-core scenarios with same cache line", "formal for protocol-level, simulation for full-chip", "coverage of all transition pairs"]},

    # --- Emulation / FPGA ---
    {"domain": "design_verification", "topic": "Emulation", "difficulty": "intermediate",
     "question_text": "When would you use hardware emulation instead of simulation? What design changes are needed to map RTL to an emulator?",
     "expected_points": ["emulation for firmware bring-up and system-level testing", "1000x faster than simulation", "need synthesizable testbench", "no delays or force/release", "memory models may need mapping", "DPI calls replaced with transactors"]},
    {"domain": "design_verification", "topic": "Emulation", "difficulty": "advanced",
     "question_text": "Your gate-level simulation takes 3 weeks per test. How would you set up an emulation-based regression? What are the main challenges?",
     "expected_points": ["compile design for emulator FPGA", "transactor-based testbench interface", "speed-bridge for BFM-to-emulator data", "limited debug visibility vs simulation", "waveform capture only in regions of interest", "cost and resource sharing"]},

    # --- Clock Domain Crossing ---
    {"domain": "design_verification", "topic": "CDC", "difficulty": "basic",
     "question_text": "What is a clock domain crossing (CDC) issue? What's the simplest synchronizer and when does it fail?",
     "expected_points": ["signal crosses between different clock domains", "metastability if sampled during transition", "two-flop synchronizer for single bit", "fails for multi-bit signals", "MTBF calculation for reliability"]},
    {"domain": "design_verification", "topic": "CDC", "difficulty": "intermediate",
     "question_text": "How do you verify CDC paths? What tools and techniques are used beyond lint checking?",
     "expected_points": ["CDC lint tools (Spyglass, Meridian)", "structural checks for synchronizers", "protocol checks for handshake signals", "gray code verification for counters", "metastability injection in simulation"]},
    {"domain": "design_verification", "topic": "CDC", "difficulty": "advanced",
     "question_text": "You have an asynchronous FIFO with gray-coded pointers crossing clock domains. How do you verify it doesn't lose or duplicate data?",
     "expected_points": ["check gray code differs by exactly one bit", "verify pointer synchronization latency doesn't cause overflow", "end-to-end data integrity scoreboard", "stress test with near-equal clock frequencies", "formal proof of no data loss property"]},

    # --- Low Power Verification ---
    {"domain": "design_verification", "topic": "Low Power", "difficulty": "intermediate",
     "question_text": "What is UPF and how does it affect verification? What new bugs can power-aware simulation find?",
     "expected_points": ["Unified Power Format defines power intent", "isolation cell behavior verification", "retention register save/restore checking", "power sequencing validation", "corruption of state during power down"]},
    {"domain": "design_verification", "topic": "Low Power", "difficulty": "advanced",
     "question_text": "Your design has 4 power domains with different shutdown sequences. How do you verify that no data corruption occurs during power transitions?",
     "expected_points": ["verify isolation cells clamp outputs correctly", "retention registers save before shutdown", "power-up sequence doesn't glitch active domains", "verify always-on logic is truly always-on", "test all legal power state transitions"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "basic", "question_text": "What is the difference between a UVM driver and a UVM monitor? Can a monitor be active?", "expected_points": ["driver drives stimulus onto the interface", "monitor only observes/samples signals", "monitor is passive, never drives", "monitor sends sampled transactions to scoreboard/coverage"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "basic", "question_text": "What is the difference between an active and a passive UVM agent?", "expected_points": ["active has sequencer+driver+monitor", "passive has only monitor", "active drives stimulus", "passive used for observing an already-driven interface"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "intermediate", "question_text": "What is a UVM sequence and how does it reach the driver through the sequencer?", "expected_points": ["sequence generates transactions", "start_item/finish_item handshake", "sequencer arbitrates between sequences", "driver pulls items via seq_item_port"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "intermediate", "question_text": "Why do we need a virtual sequence, and what problem does it solve?", "expected_points": ["coordinates multiple sequencers/agents", "synchronizes stimulus across interfaces", "single point of control for system-level scenarios", "avoids race between independent sequences"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "intermediate", "question_text": "What is the uvm_config_db used for, and when do you set versus get?", "expected_points": ["passes config/handles down the hierarchy", "set in higher component (test/env) in build phase", "get in lower component build phase", "commonly used for virtual interface handle"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "advanced", "question_text": "What is a UVM RAL model and how do you keep it in sync with the DUT registers?", "expected_points": ["register abstraction layer mirrors DUT registers", "frontdoor vs backdoor access", "predictor/adapter update the mirror", "mirror vs desired vs actual value", "explicit vs implicit prediction"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "basic", "question_text": "What is inheritance in SystemVerilog and why is it useful in a testbench?", "expected_points": ["derive a class from a base class", "reuse and extend behavior", "enables polymorphism/factory overrides", "test variations without duplicating code"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "intermediate", "question_text": "Difference between fork-join, fork-join_any and fork-join_none?", "expected_points": ["join waits for all threads", "join_any waits for the first", "join_none spawns without waiting", "choice controls synchronization of parallel stimulus"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "intermediate", "question_text": "What is a semaphore in SystemVerilog and in what scenario would you use it?", "expected_points": ["controls access to a shared resource", "get/put keys", "prevents two drivers hitting same bus", "models mutual exclusion"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "intermediate", "question_text": "Difference between a module and a program block, and how does a program block avoid races?", "expected_points": ["program executes in the reactive region", "separates TB from DUT scheduling", "avoids race between stimulus and DUT sampling", "limited procedural constructs"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "advanced", "question_text": "What is DPI, and explain DPI import versus export.", "expected_points": ["Direct Programming Interface to C", "import calls C from SV", "export exposes SV tasks to C", "used for reference models/checkers"]},
    {"domain": "design_verification", "topic": "Constrained Random", "difficulty": "intermediate", "question_text": "How does randc behave, and how is it different from rand?", "expected_points": ["randc is cyclic, no repeat until all values used", "rand is uniform each time", "randc keeps internal state", "use randc for full coverage of a small range"]},
    {"domain": "design_verification", "topic": "Coverage", "difficulty": "advanced", "question_text": "How would you test the functionality of interrupts using functional coverage?", "expected_points": ["cover interrupt assertion and de-assertion", "cover latency bins", "cross interrupt with priority/mask", "transition bins 0->1->0", "cover nested/back-to-back interrupts"]},
    {"domain": "design_verification", "topic": "Assertions", "difficulty": "advanced", "question_text": "How does the implication operator work in SVA, and what is the difference between |-> and |=>?", "expected_points": ["antecedent gates the consequent", "|-> same cycle overlap", "|=> next-cycle non-overlap", "vacuous success when antecedent false"]},
    {"domain": "physical_design", "topic": "Power Planning", "difficulty": "basic", "question_text": "Why are decoupling capacitors used in a chip, and where do you place them?", "expected_points": ["supply charge reservoir for switching current", "reduce dynamic IR drop / di-dt noise", "placed near high-activity cells and macros", "fill unused area"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "basic", "question_text": "What is SPEF and why is it important in physical design?", "expected_points": ["Standard Parasitic Exchange Format", "holds extracted R and C per net", "drives post-route timing/SI analysis", "accuracy depends on extraction corner"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "intermediate", "question_text": "What factors influence the choice of clock tree topology?", "expected_points": ["skew and insertion delay targets", "power budget", "number of sinks and their spread", "OCV/derating and NDR", "H-tree vs mesh vs multisource"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "intermediate", "question_text": "What is clock gating and why is it used?", "expected_points": ["disables clock to idle logic", "cuts dynamic power", "integrated clock gating cells", "affects clock tree structure and testability"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "advanced", "question_text": "What techniques do you use for clock skew optimization?", "expected_points": ["useful skew to borrow time", "balancing insertion delay", "clustering sinks", "NDR and shielding on clock nets", "CCD/concurrent clock and data"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "intermediate", "question_text": "What is On-Chip Variation (OCV) and how does it impact timing analysis?", "expected_points": ["local process/voltage/temp variation", "derate launch vs capture paths", "AOCV/POCV refine pessimism", "CPPR/CRPR removes common-path pessimism"]},
    {"domain": "physical_design", "topic": "Routing", "difficulty": "intermediate", "question_text": "What is metal fill insertion and why is it needed?", "expected_points": ["meets metal density DRC rules", "improves CMP planarity", "adds parasitic capacitance", "floating vs grounded fill tradeoff"]},
    {"domain": "physical_design", "topic": "Routing", "difficulty": "advanced", "question_text": "How do you handle crosstalk and signal integrity issues after routing?", "expected_points": ["identify aggressor/victim nets", "spacing and shielding", "NDR / wire widening", "buffer insertion, layer promotion", "SI-aware timing (delta delay)"]},
    {"domain": "physical_design", "topic": "Power Planning", "difficulty": "intermediate", "question_text": "What is leakage power and how can it be reduced?", "expected_points": ["subthreshold/gate leakage", "multi-Vt cell swapping", "power gating / MTCMOS", "body biasing", "reduce always-on area"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "basic", "question_text": "What is pin/pad assignment in floorplanning and what drives it?", "expected_points": ["place IO to shorten critical nets", "match package/bump map", "group by power domain", "avoid congestion at boundary"]},
    {"domain": "physical_design", "topic": "Placement", "difficulty": "intermediate", "question_text": "From a physical-design view, what changes between a 14nm and a 7nm node?", "expected_points": ["FinFET, more restrictive DRC", "higher density and congestion", "multi-patterning/coloring", "increased EM/IR concern", "routing resource pressure"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "basic", "question_text": "What is matching, what are the types, and what happens if you don't match devices?", "expected_points": ["making devices behave identically", "random vs systematic mismatch", "offset/gain error in diff pairs and mirrors", "techniques: common-centroid, interdigitation, dummies"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "basic", "question_text": "How do you match resistor and capacitor layouts?", "expected_points": ["same orientation and unit elements", "common-centroid/interdigitated", "dummies at the edges", "same surrounding environment", "for caps: unit cap array, same fringe"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "intermediate", "question_text": "What are the advantages and disadvantages of common-centroid versus interdigitated patterns?", "expected_points": ["common-centroid cancels linear gradients in 2D", "interdigitation cancels 1D gradient, simpler routing", "common-centroid needs complex routing/more parasitics", "choose by gradient direction and area"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "intermediate", "question_text": "How do you improve the matching of a current mirror or a differential pair?", "expected_points": ["common-centroid placement", "dummy devices", "same orientation, long fingers", "route symmetrically", "keep at same temperature/away from power devices"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "basic", "question_text": "What are dummy transistors and why do we add them?", "expected_points": ["provide identical edge environment", "fix etch/WPE/LOD variation at array edges", "improve matching of critical devices", "not electrically active"]},
    {"domain": "analog_layout", "topic": "Parasitic Effects", "difficulty": "intermediate", "question_text": "What are the ways to reduce metal resistance in a layout?", "expected_points": ["wider metal", "use higher/thicker layers", "more vias/contacts in parallel", "shorter routes", "parallel metals stitched"]},
    {"domain": "analog_layout", "topic": "Parasitic Effects", "difficulty": "basic", "question_text": "What is a contact and a via, and how does adding more of them reduce resistance?", "expected_points": ["contact: diffusion/poly to metal1", "via: metal to metal", "parallel vias lower resistance", "also carry more current (EM)"]},
    {"domain": "analog_layout", "topic": "Latchup", "difficulty": "intermediate", "question_text": "What is latch-up, how do you solve it, and how do you take care of it during layout?", "expected_points": ["parasitic PNPN/SCR turns on", "low-resistance well/substrate taps", "guard rings, tap spacing rule", "separate noisy from sensitive, deep n-well"]},
    {"domain": "analog_layout", "topic": "Guard Rings", "difficulty": "intermediate", "question_text": "What is a guard ring, what are the types, and how does it reduce latch-up and noise?", "expected_points": ["diffusion ring at fixed potential", "p+ (substrate) and n+ (well) rings", "collects minority carriers/low-Z path", "double guard ring for isolation"]},
    {"domain": "analog_layout", "topic": "Guard Rings", "difficulty": "advanced", "question_text": "What is deep N-well guarding and when would you use it?", "expected_points": ["isolates NMOS from noisy substrate", "separate p-well biasing", "reduces substrate coupling for sensitive analog", "area/cost tradeoff"]},
    {"domain": "analog_layout", "topic": "ESD", "difficulty": "basic", "question_text": "What is ESD and how do you fix ESD problems in the layout?", "expected_points": ["electrostatic discharge damages gates", "clamp/diode protection at pads", "wide metal and many contacts on discharge path", "ballast resistance, salicide block"]},
    {"domain": "analog_layout", "topic": "Antenna", "difficulty": "intermediate", "question_text": "What is the antenna effect, where do the charges come from, and how do jumpers and diodes help?", "expected_points": ["charge collected on long metal during etch", "damages thin gate oxide", "break net with higher-layer jumper", "add antenna/protection diode to discharge"]},
    {"domain": "analog_layout", "topic": "Shielding", "difficulty": "intermediate", "question_text": "What is shielding, which signals do you shield and why, and what happens without it?", "expected_points": ["ground/quiet line beside/around sensitive net", "protect high-Z, small-signal, clock nets", "reduces crosstalk/coupling", "without it: noise injection, offset, jitter"]},
    {"domain": "analog_layout", "topic": "Electromigration", "difficulty": "intermediate", "question_text": "Describe the electromigration effect and ways to reduce it during layout.", "expected_points": ["momentum transfer moves metal atoms at high current density", "voids/hillocks, opens/shorts", "widen metal, more vias", "follow Jmax rules, split current"]},
    {"domain": "analog_layout", "topic": "Process Effects", "difficulty": "advanced", "question_text": "What are WPE, LOD and STI stress, and how do they affect matching?", "expected_points": ["well proximity effect shifts Vt near well edge", "length of diffusion / STI stress changes mobility", "keep matched devices same distance from well edge", "use dummies and uniform OD"]},
    {"domain": "analog_layout", "topic": "Floorplanning", "difficulty": "intermediate", "question_text": "How do you plan device placement in an analog block and separate analog from digital?", "expected_points": ["group by function/signal flow", "symmetry for differential structures", "physical separation + guard rings", "separate supplies/grounds, keep digital noise away"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "basic", "question_text": "What is the UVM factory and why do we use it instead of calling new directly?", "expected_points": ["registers types for override", "enables type/instance overrides without editing TB", "create() vs new", "supports reuse and test-specific variants"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "basic", "question_text": "What is a UVM objection and how does it control the end of a phase?", "expected_points": ["raise/drop objection", "phase ends when all objections dropped", "keeps sim alive while stimulus runs", "drain time"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "intermediate", "question_text": "What is a TLM analysis port, and how does a monitor use it to reach the scoreboard and coverage?", "expected_points": ["analysis port broadcasts transactions", "monitor writes, subscribers implement write()", "one-to-many connection", "decouples monitor from checkers"]},
    {"domain": "design_verification", "topic": "UVM", "difficulty": "basic", "question_text": "What is the difference between get_next_item and try_next_item in a UVM driver?", "expected_points": ["get_next_item blocks until item available", "try_next_item is non-blocking, returns null", "item_done handshake", "use try for idle/backpressure modelling"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "basic", "question_text": "What is the difference between a task and a function in SystemVerilog?", "expected_points": ["function returns a value, no time consumption", "task can consume time (delays, waits)", "function cannot call a task", "task for stimulus, function for computation"]},
    {"domain": "design_verification", "topic": "SystemVerilog", "difficulty": "basic", "question_text": "What is a mailbox and how is it used between testbench components?", "expected_points": ["FIFO for passing objects between threads", "put/get blocking, try_put/try_get non-blocking", "bounded vs unbounded", "e.g. generator to driver"]},
    {"domain": "design_verification", "topic": "Coverage", "difficulty": "basic", "question_text": "What is a covergroup and what event triggers its sampling?", "expected_points": ["container of coverpoints/crosses", "sampled on an event or explicit sample()", "bins record hit values", "tied to functional intent"]},
    {"domain": "design_verification", "topic": "Coverage", "difficulty": "intermediate", "question_text": "What are ignore_bins and illegal_bins, and when would you use each?", "expected_points": ["ignore_bins excluded from coverage", "illegal_bins flag an error if hit", "ignore for don't-care values", "illegal for values that must never occur"]},
    {"domain": "design_verification", "topic": "Debug", "difficulty": "basic", "question_text": "What is the difference between $display, $monitor and $strobe?", "expected_points": ["$display prints immediately", "$monitor prints on any change", "$strobe prints at end of time step (post-NBA)", "region/timing differences"]},
    {"domain": "design_verification", "topic": "Constrained Random", "difficulty": "intermediate", "question_text": "Your constrained-random test keeps generating similar transactions. What could be wrong with your constraints?", "expected_points": ["over-constrained / narrow ranges", "missing dist weighting", "solver bias without dist", "seed not varying", "need functional coverage feedback"]},
    {"domain": "physical_design", "topic": "Placement", "difficulty": "basic", "question_text": "What is the difference between placement and routing?", "expected_points": ["placement fixes cell locations", "routing connects pins with metal", "placement optimizes timing/congestion first", "routing must obey DRC and layers"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "basic", "question_text": "What is utilization in a floorplan, and how does it affect the design?", "expected_points": ["ratio of cell area to core area", "too high -> congestion/routing failure", "too low -> wasted area/longer wires", "leave room for buffers/CTS"]},
    {"domain": "physical_design", "topic": "Floorplanning", "difficulty": "basic", "question_text": "What input files do you need to start physical design?", "expected_points": ["synthesized gate-level netlist", "SDC timing constraints", "LEF/tech + std-cell libs", "Liberty (.lib) timing", "UPF for low power"]},
    {"domain": "physical_design", "topic": "CTS", "difficulty": "intermediate", "question_text": "What is useful skew and how does it help timing closure?", "expected_points": ["intentionally delaying/advancing clock to a flop", "borrows time from slack-rich to slack-poor path", "fixes setup without touching data path", "risk of hold degradation"]},
    {"domain": "physical_design", "topic": "Routing", "difficulty": "intermediate", "question_text": "What is a max transition or max capacitance violation, and how do you fix it?", "expected_points": ["slew/cap exceeds library limit", "upsize driver, add buffer", "reduce fanout/wire length", "split net, higher metal layer"]},
    {"domain": "physical_design", "topic": "DRC/LVS", "difficulty": "basic", "question_text": "What is a well tap / tie cell and why is it needed?", "expected_points": ["well tap ties well/substrate to supply", "prevents latch-up", "tie-hi/tie-lo avoid floating gate inputs", "placed per max-distance rule"]},
    {"domain": "physical_design", "topic": "Timing Closure", "difficulty": "advanced", "question_text": "After routing you have a large negative TNS across many paths. How do you approach it systematically?", "expected_points": ["group paths, find common cause (region/clock/net)", "fix worst path groups first", "placement/useful skew/sizing", "check congestion and SI", "incremental ECO and re-time"]},
    {"domain": "physical_design", "topic": "STA", "difficulty": "basic", "question_text": "In simple terms, what is a setup violation and what is a hold violation?", "expected_points": ["setup: data arrives too late before clock edge", "hold: data changes too soon after clock edge", "setup fixed by faster path/slower clock", "hold fixed by adding delay"]},
    {"domain": "analog_layout", "topic": "Transistor", "difficulty": "basic", "question_text": "Draw and explain the terminals of an NMOS and a PMOS transistor and where each connects.", "expected_points": ["gate, source, drain, body", "NMOS body to lowest potential/gnd", "PMOS body to highest potential/VDD", "conduction by gate voltage"]},
    {"domain": "analog_layout", "topic": "Transistor", "difficulty": "basic", "question_text": "What is threshold voltage, and what layout factors can shift it?", "expected_points": ["gate voltage to form channel", "WPE, STI stress, LOD shift Vt", "matching needs consistent surroundings", "body bias effect"]},
    {"domain": "analog_layout", "topic": "Transistor", "difficulty": "intermediate", "question_text": "What is channel length modulation and why does it matter for analog design?", "expected_points": ["effective L shrinks with Vds", "finite output resistance", "affects gain of current sources/amplifiers", "use longer L for better ro"]},
    {"domain": "analog_layout", "topic": "Transistor", "difficulty": "intermediate", "question_text": "What is subthreshold leakage, and what is the hot-electron effect?", "expected_points": ["conduction below Vt (exponential)", "leakage/standby power", "hot carriers damage oxide over time", "reliability/aging concern"]},
    {"domain": "analog_layout", "topic": "Technology", "difficulty": "basic", "question_text": "What is the difference between higher and lower node technologies for a layout engineer?", "expected_points": ["lower node: denser, more DRC rules", "multi-patterning/coloring", "higher parasitics/variation", "FinFET vs planar"]},
    {"domain": "analog_layout", "topic": "Technology", "difficulty": "intermediate", "question_text": "What is the difference between a CMOS (planar) and a FinFET device, and how does it change layout?", "expected_points": ["FinFET has 3D fin, better control", "width quantized by fin count", "fixed poly pitch, restrictive rules", "less leakage, better matching"]},
    {"domain": "analog_layout", "topic": "Standard Cells", "difficulty": "basic", "question_text": "How do you decide the height of a standard cell, and what are track and pitch?", "expected_points": ["height in number of routing tracks", "track = routing grid line", "pitch = min spacing between tracks/metals", "taller cell = more drive/routing room"]},
    {"domain": "analog_layout", "topic": "Process Effects", "difficulty": "intermediate", "question_text": "What is DFM (design for manufacturability) and give examples in layout.", "expected_points": ["improve yield/robustness", "redundant vias, wider spacing", "metal fill, avoid single vias", "litho-friendly shapes"]},
    {"domain": "analog_layout", "topic": "Power Layout", "difficulty": "intermediate", "question_text": "How do you choose and route power metal in an analog layout?", "expected_points": ["width sized for current (EM/IR)", "top thick metals for supply", "multiple vias at crossings", "separate analog/digital supplies"]},
    {"domain": "analog_layout", "topic": "Electromigration", "difficulty": "intermediate", "question_text": "How do you calculate the required metal width for a given current to meet EM rules?", "expected_points": ["current density Jmax per layer", "width = I / (Jmax * thickness)", "derate for temperature", "widen or add parallel metal/vias"]},
    {"domain": "analog_layout", "topic": "Matching", "difficulty": "basic", "question_text": "What is the difference between random and systematic mismatch, and how does layout address each?", "expected_points": ["random: area-dependent (Pelgrom), use larger devices", "systematic: gradients/process, use common-centroid", "dummies for edge effects", "symmetry and same orientation"]},
]

def seed():
    """Insert all seed questions into the question bank (skip duplicates)."""
    database.init_db()
    added = 0
    skipped = 0
    for q in QUESTIONS:
        existing = database.get_question_bank(
            domain=q["domain"], topic=q["topic"], limit=100
        )
        if any(e["question_text"].strip() == q["question_text"].strip() for e in existing):
            skipped += 1
            continue
        qid = database.add_question_to_bank(
            domain=q["domain"],
            topic=q["topic"],
            difficulty=q["difficulty"],
            question_text=q["question_text"],
            expected_points=q.get("expected_points", []),
            level=q.get("level", "all"),
            tags=q.get("tags", []),
        )
        if qid:
            added += 1
            print(f"  Added #{qid}: [{q['domain']}/{q['topic']}] {q['question_text'][:60]}...")
    print(f"\nSeeded {added} new, {skipped} already existed (out of {len(QUESTIONS)} total).")

if __name__ == "__main__":
    seed()
